name: 'slabruyere/use-private-action'
description: 'This action allows the use of custom actions in private GitHub repositories.'
author: 'slabruyere'
branding: 
  icon: 'external-link'
  color: 'gray-dark'
inputs:
  private-action:
    description: 'Private action to execute, format: {org}/{repo}[/path]@ref'
    required: true
  private-action-token:
    description: 'Token to access the private repository'
    required: true
  private-action-folder:
    description: 'Folder in which to clone the private action'
    required: false
runs:
  using: 'node12'
  main: 'dist/main.js'
